### ISSUE TITLE
Quais itens devemos mostrar no setup?

### ISSUE THREAD

**Issue by fernandofleury** [react-brasil/my-setup#1]
Eu pensei em algumas coisas tipo:

- Editor
  - Color Scheme
  - Font
  - Plugins

- Terminal
  - Color Scheme
  - Font
  - Shell

Ferramentas de produtividade talvez? A ideia era não complicar muito

Por exemplo:

```
Editor: vscode-insiders
Plugins: Atom Keymap, Auto Close Tag, Clipboard History, Color Highlight, Editorconfig, ES7 snippets, Eslint, Prettier, file-icons, Settings sync
Color Scheme: Material Palenight
Font: Dank Mono
```

SS do color scheme:
![image](https://user-images.githubusercontent.com/2780941/41659441-9db128a4-7499-11e8-819d-4f3fa69c36d2.png)

**Comment by enieber** [comment]
ferramentas de produtividade seria interessante se fosse
- gerenciador de tarefas
- gerenciador de tempo

**Comment by enieber** [comment]
# Setup

**Notebook:** Lenovo basicão

**SO**: Arch Linux <Manjaro>

**IDE**: Neovim

**Terminal**: Terminal do Manjaro + TMUX

**Extra**: Docker, Tmuxinator

**Comment by enieber** [comment]
@fernandofleury esse layout ficou legal, o pessoal esta usando no slack

**Comment by fernandofleury** [comment]
boa
